# Generated by Django 3.0.5 on 2020-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coordinatesX', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coordinatesY', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
