# Generated by Django 3.0.5 on 2020-06-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinatesX',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='coordinatesY',
        ),
    ]
