# Generated by Django 3.0.5 on 2020-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200601_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=50.0, max_digits=9),
            preserve_default=False,
        ),
    ]
